# Generated by Django 5.1.4 on 2025-01-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_product_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
